### ISSUE TITLE
How to integrate it on page?

### ISSUE THREAD

**Issue by PixsaOJ** [awsmin/wp-job-openings#6] opened 2020-08-12 12:45 UTC
Hi, can someone tell me how to get same result as [this 
](https://demo.awsm.in/wp-job-openings/)

Is this only demo? Or can i have same design on my website

**Comment by anantajitjg** [comment] 2020-08-13 17:34
The demo site is built using a custom WordPress theme. You can use any WordPress theme for your purpose. We have tested our plugin, with popular themes in WordPress. After activating and setting up our plugin, if you are not satisfied with the UI, you can apply custom CSS in the Customizer's(Appearance > Customize from WordPress admin dashboard) additional CSS section to improve the UI according to your need.

**Please use the support forum of WP Job Openings(https://wordpress.org/support/plugin/wp-job-openings/) for support requests.**

If you have found any bug related to our plugin, then please share us the below details:

- Bug description
- Steps to reproduce this issue with Screenshots (if any)
- The version of WP Job Openings plugin
- WordPress Version
- Web Browser with Version

We are closing this issue since it falls under support requests. Please feel free to create an issue in GitHub, if you have found any bug or have a feature request.

**Closed by anantajitjg** 2020-08-13 17:34 UTC
