### ISSUE TITLE
How to add only filters in widgets?

### ISSUE THREAD

**Issue by mayeed920** [awsmin/wp-job-openings#24] opened 2021-07-02 23:58 UTC
How can i add only filters area in widgets? 
so i can put it in the footer section
there is no space to list any job there
and when anyone searches or choose spec it must take him to the listing page

**Comment by anantajitjg** [comment] 2021-07-05 06:52
Currently, there is no direct way to do this. You may need to create a custom solution with code to achieve this. You can use the `AWSM_Job_Openings_Filters::display_filter_form` function to display the filter form and `awsmjobs_filtered_listings` JS Event for redirecting to the job listing page. I hope this will be useful for you.

https://github.com/awsmin/wp-job-openings/blob/0470a6c088343b5bfd568be4a6092c995bf15010/inc/class-awsm-job-openings-filters.php#L24-L27

**Note:** Please use the [GitHub discussions](https://github.com/awsmin/wp-job-openings/discussions) or [support forum of WP Job Openings](https://wordpress.org/support/plugin/wp-job-openings/) for support requests. We are closing this issue since it falls under support requests.

If you have found any bug related to our plugin or if you have a feature request, please feel free to create an issue in GitHub with the below details:

**Bug report:**

* Summary
* Description
     * Expected Behavior
     * Actual Behavior
* Steps to reproduce this issue with Screenshots (if any)
* The version of WP Job Openings plugin
* WordPress Version
* Web Browser with Version

**Feature request:**

* Summary
* Description
* Suggestions (if any)
* Screenshots (if any)

Thanks for using our plugin 🙂

**Closed by anantajitjg** 2021-07-05 06:52 UTC
