### ISSUE TITLE
Error in submissions 

### ISSUE THREAD

**Issue by hamzed88** [awsmin/wp-job-openings#4] opened 2020-04-17 09:00 UTC
Whenever users try to submit applications they receive error in submitting try again later

**Comment by anantajitjg** [comment] 2020-04-20 06:24
@hamzed88 Hi, please use the support forum of WP Job Openings for support requests. We hope your question has been answered in the support forum: [https://wordpress.org/support/topic/error-in-submitting-application/](https://wordpress.org/support/topic/error-in-submitting-application/)
If you have found any bug related to our plugin, then please share us the below details:
- Bug description
- Steps to reproduce this issue with Screenshots (if any)
- The version of WP Job Openings plugin
- WordPress Version
- Web Browser with Version

We are closing this issue since it falls under support requests. Please feel free to create an issue in GitHub, if you have found any bug related to our plugin.
Thanks for using our plugin 🙂

**Closed by anantajitjg** 2020-04-20 06:24 UTC
