### ISSUE TITLE
Multiple businesses

### ISSUE THREAD

**Issue by SaltyPotato** [awsmin/wp-job-openings#9] opened 2020-11-05 16:15 UTC
Hello,

Can I add multiple businesses with custom settings?

**Comment by anantajitjg** [comment] 2020-11-06 08:22
If you are referring to the job board, please note that our plugin is built focusing on a particular company's job listing, not as a job board plugin. But if you are a developer, you can easily customize our plugin to a job board without editing a single line of code in the plugin. Please refer to this link for more details: https://docs.wpjobopenings.com/job-listing/customizing-templates-of-your-job-listings

Also, please use the support forum of WP Job Openings for support requests. We are closing this issue since it falls under support requests. If you have any other queries, please create the same in our support forum: https://wordpress.org/support/plugin/wp-job-openings/

If you have found any bug related to our plugin or if you have a feature request, please feel free to create an issue in GitHub with the below details:

**Bug report:**

* Summary
* Description
     * Expected Behavior
     * Actual Behavior
* Steps to reproduce this issue with Screenshots (if any)
* The version of WP Job Openings plugin
* WordPress Version
* Web Browser with Version

**Feature request:**

* Summary
* Description
* Suggestions (if any)
* Screenshots (if any)

Thanks for using our plugin 🙂

**Closed by anantajitjg** 2020-11-06 08:22 UTC

**Comment by SaltyPotato** [comment] 2020-11-06 09:40
Can I override the `applicant_notification()` method using a hook in my child theme?

I need to change some of the email headers.

**Comment by anantajitjg** [comment] 2020-11-06 10:21
To change the email headers you can use these hooks:

https://github.com/awsmin/wp-job-openings/blob/15764a4833b83f46b8016565797cf306628dbeb8/inc/class-awsm-job-openings-form.php#L628-L636

https://github.com/awsmin/wp-job-openings/blob/15764a4833b83f46b8016565797cf306628dbeb8/inc/class-awsm-job-openings-form.php#L734-L743

**Comment by SaltyPotato** [comment] 2020-11-06 10:33
Can I also get the job details when hooking in to this filter?

**Comment by anantajitjg** [comment] 2020-11-06 10:57
You can use `$applicant_details['awsm_job_id']` to get the Job ID and the same can be used to retrieve the ACF field value. Please note that currently, this will be only available for the `awsm_jobs_admin_notification_mail_headers` hook. We will add the same for `awsm_jobs_applicant_notification_mail_headers` hook in the upcoming version of WP Job Openings.

**Comment by SaltyPotato** [comment] 2020-11-06 11:07
When can we expect this new version?

**Comment by anantajitjg** [comment] 2020-11-06 11:20
So sorry! currently, we can't give an ETA. If this is urgent, you can make this change in the plugin file itself. The same will be available in the next version when the plugin gets updated. So there won't be an issue. I hope this helps 🙂 

```
$headers = apply_filters( 
 	'awsm_jobs_applicant_notification_mail_headers', 
 	array( 
 		'content_type' => 'Content-Type: text/html; charset=UTF-8', 
 		'from'         => sprintf( 'From: %1$s <%2$s>', $from, $from_email ), 
 		'reply_to'     => 'Reply-To: ' . $reply_to, 
 		'cc'           => 'Cc: ' . $applicant_cc, 
 	) ,
       $applicant_details
 ); 
```
